version: '3.4'

services:
  xaccountserver:
    image: ${DOCKER_REGISTRY-}xaccountserver
    build:
      context: .
      dockerfile: XAccountServer/Dockerfile

  xgameserver:
    image: ${DOCKER_REGISTRY-}xgameserver
    build:
      context: .
      dockerfile: XGameServer/Dockerfile

