name: Custom Postgres Build

on:
  push:
    branches: [ "main", "feat/migration-to-console" ]
    paths:
      - docker/postgres/**
      - .github/workflows/postgres-build.yml

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: mir-eternal/postgres
        tags: latest
        registry: docker.pkg.github.com
        dockerfile: ./docker/postgres/Dockerfile
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}